### ISSUE TITLE
remove date from display

### ISSUE THREAD

**Issue by DaniGr** [fzesch/lagesonum#62]
Actual: "These numbers have been entered since 10/1/15, 12:26 AM by at least 3 different persons."
This date is confusing as it doesn't have any relation to the actual display the people are looking at.

Just write e.g.: "The following numbers have been entered into the system within the last XX minutes"

**Comment by pitpalme** [comment]
Beta already contains text "These numbers have been entered _latest_ since". Plus time will always be midnight, instead of minute-precise.

I think we should keep the date as kind of an easy to catch reference. 5 days in minutes will be a huge number :smile_cat: 
But I might be wrong :smile:

**Comment by DaniGr** [comment]
But I thought we agreed that the display shows the last 18 numbers entered 3 times or more? So no time at all needed?
"Peter Palmreuther [23:28] 
OK. Die letzten 18 Nummern. Chronologisch nach Eingabezeitpunkt. Kriegen wir hin. "

**Comment by pitpalme** [comment]
OK. Wen can do this.

OTOH it was said LaGeSo is about to enter a whole bunch of numbers (and therefore spreadsheet interface was discussed). 
1. Does a count of 18 still hold the requirements? I mean: if LaGeSo entered 25 numbers it doesn't make sense to display only 18, then. Do we need some more precise description, about how many numbers actually should be shown?
2. Doesn't make any kind of timing reference (whatever it will be) sense, to know "These 18/25/50/whatever numbers are not older than XX (minutes/days/weeks/months/years)."? I mean: "within the last XX minutes" is such a kind of a reference. Does it scale good enough? Lets say it's 6 hours, this makes 360 minutes. Do people understand the intended reference easier, if it's "360 minutes" and not "since Oct., 9th, 2015 08:00"? Or do LaGeSo entered numbers change that frequently, we're not going to have more than, let's say, 60 minutes?

I'm willing to change to whatever is required, but I don't want to change back and forth and even once more, only because it's not been thought about enough, in advance.
So what's the user story?

```
Show latest 18 numbers entered 3 times or more or by LaGeSo.
Declare, it's the latest ones.
Declare, it's been entered at least 3 times or by LaGeSo.
Don't mind about timing.
```

or

```
Show latest 18 numbers entered 3 times or more or by LaGeSo if younger than XX days.
Declare, it's the latest ones.
Declare, it's been entered at least 3 times or by LaGeSo.
Say it's "since XX minutes", no matter how big XX is.
```

??? Or anything else?

I'm not talking about the mid- and longterm vision yet. I'm only talking about: "What to show right now?".

**Comment by fzesch** [comment]
How about "Shown today" and order them by time of appearance and include the time when they where last shown? This should scale well enough.

**Comment by DaniGr** [comment]
The display was originally designed to mirror the actual display on site by means of measuring user input. That was the user story. I don't know why it was done completely different but I'm generally ok with displaying other kinds of filters or information. But don't call it display then. The display as it has been now live for a much too long period of time is plain confusing and makes the website seem broken and unused. For now I vote for: Disable the display until we have a working and understandable solution please.

**Comment by fzesch** [comment]
Display will be disabled in new design, anyway
